# Generated by Django 2.1.2 on 2018-10-25 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_i18n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helloworldprocess',
            options={'verbose_name': 'Claim Request', 'verbose_name_plural': 'Claim Requests'},
        ),
        migrations.AddField(
            model_name='helloworldprocess',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
