# Generated by Django 2.1.2 on 2018-10-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('helloworld', '0003_auto_20181025_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelloWorldProcess',
            new_name='ClaimProcess',
        ),
    ]
