# Generated by Django 2.1.2 on 2018-10-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20181025_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimprocess',
            options={'verbose_name': 'Claim_Request', 'verbose_name_plural': 'Claim_Requests'},
        ),
    ]
