# Generated by Django 2.1.2 on 2018-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_auto_20181025_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimprocess',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='claimprocess',
            name='business_of_insured',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimprocess',
            name='class_of_business',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimprocess',
            name='consequence_of_loss',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimprocess',
            name='location_loss',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
