# Generated by Django 2.1.2 on 2018-10-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20181025_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimprocess',
            old_name='location_loss',
            new_name='location_of_loss',
        ),
    ]
