# Generated by Django 2.1.2 on 2018-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_auto_20181025_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimprocess',
            name='date_of_loss_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='claimprocess',
            name='date_of_loss_to',
            field=models.DateField(null=True),
        ),
    ]
